/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.linkedin.kytea;

public class KyteaSentence {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected KyteaSentence(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KyteaSentence obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LiKyteaJNI.delete_KyteaSentence(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSurface(SWIGTYPE_p_KyteaString value) {
    LiKyteaJNI.KyteaSentence_surface_set(swigCPtr, this, SWIGTYPE_p_KyteaString.getCPtr(value));
  }

  public SWIGTYPE_p_KyteaString getSurface() {
    return new SWIGTYPE_p_KyteaString(LiKyteaJNI.KyteaSentence_surface_get(swigCPtr, this), true);
  }

  public void setNorm(SWIGTYPE_p_KyteaString value) {
    LiKyteaJNI.KyteaSentence_norm_set(swigCPtr, this, SWIGTYPE_p_KyteaString.getCPtr(value));
  }

  public SWIGTYPE_p_KyteaString getNorm() {
    return new SWIGTYPE_p_KyteaString(LiKyteaJNI.KyteaSentence_norm_get(swigCPtr, this), true);
  }

  public void setWsConfs(SWIGTYPE_p_std__vectorT_double_t value) {
    LiKyteaJNI.KyteaSentence_wsConfs_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_double_t getWsConfs() {
    long cPtr = LiKyteaJNI.KyteaSentence_wsConfs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_double_t(cPtr, false);
  }

  public void setWords(SWIGTYPE_p_std__vectorT_kytea__KyteaWord_t value) {
    LiKyteaJNI.KyteaSentence_words_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_kytea__KyteaWord_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_kytea__KyteaWord_t getWords() {
    long cPtr = LiKyteaJNI.KyteaSentence_words_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_kytea__KyteaWord_t(cPtr, false);
  }

  public KyteaSentence() {
    this(LiKyteaJNI.new_KyteaSentence__SWIG_0(), true);
  }

  public KyteaSentence(SWIGTYPE_p_KyteaString str, SWIGTYPE_p_KyteaString norm_str) {
    this(LiKyteaJNI.new_KyteaSentence__SWIG_1(SWIGTYPE_p_KyteaString.getCPtr(str), SWIGTYPE_p_KyteaString.getCPtr(norm_str)), true);
  }

  public void refreshWS(double confidence) {
    LiKyteaJNI.KyteaSentence_refreshWS(swigCPtr, this, confidence);
  }

}
