/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.linkedin.kytea;

public class KyteaWord {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected KyteaWord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KyteaWord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LiKyteaJNI.delete_KyteaWord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public KyteaWord(SWIGTYPE_p_KyteaString s, SWIGTYPE_p_KyteaString n) {
    this(LiKyteaJNI.new_KyteaWord(SWIGTYPE_p_KyteaString.getCPtr(s), SWIGTYPE_p_KyteaString.getCPtr(n)), true);
  }

  public void setSurface(SWIGTYPE_p_KyteaString value) {
    LiKyteaJNI.KyteaWord_surface_set(swigCPtr, this, SWIGTYPE_p_KyteaString.getCPtr(value));
  }

  public SWIGTYPE_p_KyteaString getSurface() {
    return new SWIGTYPE_p_KyteaString(LiKyteaJNI.KyteaWord_surface_get(swigCPtr, this), true);
  }

  public void setNorm(SWIGTYPE_p_KyteaString value) {
    LiKyteaJNI.KyteaWord_norm_set(swigCPtr, this, SWIGTYPE_p_KyteaString.getCPtr(value));
  }

  public SWIGTYPE_p_KyteaString getNorm() {
    return new SWIGTYPE_p_KyteaString(LiKyteaJNI.KyteaWord_norm_get(swigCPtr, this), true);
  }

  public void setTags(SWIGTYPE_p_std__vectorT_std__vectorT_std__pairT_KyteaString_double_t_t_t value) {
    LiKyteaJNI.KyteaWord_tags_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_std__vectorT_std__pairT_KyteaString_double_t_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_std__vectorT_std__pairT_KyteaString_double_t_t_t getTags() {
    long cPtr = LiKyteaJNI.KyteaWord_tags_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_std__vectorT_std__pairT_KyteaString_double_t_t_t(cPtr, false);
  }

  public void setIsCertain(boolean value) {
    LiKyteaJNI.KyteaWord_isCertain_set(swigCPtr, this, value);
  }

  public boolean getIsCertain() {
    return LiKyteaJNI.KyteaWord_isCertain_get(swigCPtr, this);
  }

  public void setUnknown(boolean value) {
    LiKyteaJNI.KyteaWord_unknown_set(swigCPtr, this, value);
  }

  public boolean getUnknown() {
    return LiKyteaJNI.KyteaWord_unknown_get(swigCPtr, this);
  }

  public void limitTags(long lev, long lim) {
    LiKyteaJNI.KyteaWord_limitTags(swigCPtr, this, lev, lim);
  }

  public int getNumTags() {
    return LiKyteaJNI.KyteaWord_getNumTags(swigCPtr, this);
  }

  public SWIGTYPE_p_std__pairT_KyteaString_double_t getTag(int lev) {
    long cPtr = LiKyteaJNI.KyteaWord_getTag(swigCPtr, this, lev);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__pairT_KyteaString_double_t(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_std__pairT_KyteaString_double_t_t getTags(int lev) {
    return new SWIGTYPE_p_std__vectorT_std__pairT_KyteaString_double_t_t(LiKyteaJNI.KyteaWord_getTags(swigCPtr, this, lev), true);
  }

  public SWIGTYPE_p_KyteaString getTagSurf(int lev) {
    return new SWIGTYPE_p_KyteaString(LiKyteaJNI.KyteaWord_getTagSurf(swigCPtr, this, lev), false);
  }

  public double getTagConf(int lev) {
    return LiKyteaJNI.KyteaWord_getTagConf(swigCPtr, this, lev);
  }

  public void setTag(int lev, SWIGTYPE_p_std__pairT_KyteaString_double_t tag) {
    LiKyteaJNI.KyteaWord_setTag(swigCPtr, this, lev, SWIGTYPE_p_std__pairT_KyteaString_double_t.getCPtr(tag));
  }

  public void setTagConf(int lev, double conf) {
    LiKyteaJNI.KyteaWord_setTagConf(swigCPtr, this, lev, conf);
  }

  public void clearTags(int lev) {
    LiKyteaJNI.KyteaWord_clearTags(swigCPtr, this, lev);
  }

  public void addTag(int lev, SWIGTYPE_p_std__pairT_KyteaString_double_t tag) {
    LiKyteaJNI.KyteaWord_addTag(swigCPtr, this, lev, SWIGTYPE_p_std__pairT_KyteaString_double_t.getCPtr(tag));
  }

  public void setUnknown(boolean val) {
    LiKyteaJNI.KyteaWord_setUnknown(swigCPtr, this, val);
  }

  public boolean getUnknown() {
    return LiKyteaJNI.KyteaWord_getUnknown(swigCPtr, this);
  }

  public boolean hasTag(int lev) {
    return LiKyteaJNI.KyteaWord_hasTag(swigCPtr, this, lev);
  }

}
