/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.linkedin.kytea;

public class Kytea {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Kytea(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Kytea obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LiKyteaJNI.delete_Kytea(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void readModel(String fileName) {
    LiKyteaJNI.Kytea_readModel(swigCPtr, this, fileName);
  }

  public void writeModel(String fileName) {
    LiKyteaJNI.Kytea_writeModel(swigCPtr, this, fileName);
  }

  public void calculateWS(KyteaSentence sent) {
    LiKyteaJNI.Kytea_calculateWS(swigCPtr, this, KyteaSentence.getCPtr(sent), sent);
  }

  public void calculateTags(KyteaSentence sent, int lev) {
    LiKyteaJNI.Kytea_calculateTags(swigCPtr, this, KyteaSentence.getCPtr(sent), sent, lev);
  }

  public void calculateUnknownTag(KyteaWord str, int lev) {
    LiKyteaJNI.Kytea_calculateUnknownTag(swigCPtr, this, KyteaWord.getCPtr(str), str, lev);
  }

  public SWIGTYPE_p_kytea__StringUtil getStringUtil() {
    long cPtr = LiKyteaJNI.Kytea_getStringUtil(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_kytea__StringUtil(cPtr, false);
  }

  public SWIGTYPE_p_kytea__KyteaConfig getConfig() {
    long cPtr = LiKyteaJNI.Kytea_getConfig(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_kytea__KyteaConfig(cPtr, false);
  }

  public void trainAll() {
    LiKyteaJNI.Kytea_trainAll(swigCPtr, this);
  }

  public void analyze() {
    LiKyteaJNI.Kytea_analyze(swigCPtr, this);
  }

  public void init() {
    LiKyteaJNI.Kytea_init(swigCPtr, this);
  }

  public Kytea() {
    this(LiKyteaJNI.new_Kytea__SWIG_0(), true);
  }

  public Kytea(SWIGTYPE_p_kytea__KyteaConfig config) {
    this(LiKyteaJNI.new_Kytea__SWIG_1(SWIGTYPE_p_kytea__KyteaConfig.getCPtr(config)), true);
  }

  public SWIGTYPE_p_kytea__KyteaModel getWSModel() {
    long cPtr = LiKyteaJNI.Kytea_getWSModel(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_kytea__KyteaModel(cPtr, false);
  }

  public void setWSModel(SWIGTYPE_p_kytea__KyteaModel model) {
    LiKyteaJNI.Kytea_setWSModel(swigCPtr, this, SWIGTYPE_p_kytea__KyteaModel.getCPtr(model));
  }

  public void checkEqual(Kytea rhs) {
    LiKyteaJNI.Kytea_checkEqual(swigCPtr, this, Kytea.getCPtr(rhs), rhs);
  }

}
