/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.linkedin.kytea;

public class LiKytea {
  public static boolean __KyteaTagLessThan__(SWIGTYPE_p_std__pairT_KyteaString_double_t a, SWIGTYPE_p_std__pairT_KyteaString_double_t b) {
    return LiKyteaJNI.__KyteaTagLessThan__(SWIGTYPE_p_std__pairT_KyteaString_double_t.getCPtr(a), SWIGTYPE_p_std__pairT_KyteaString_double_t.getCPtr(b));
  }

}
