/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.linkedin.kytea;

public class Mykytea {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Mykytea(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Mykytea obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LiKyteaJNI.delete_Mykytea(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Mykytea(String str) {
    this(LiKyteaJNI.new_Mykytea(str), true);
  }

  public StringVector getWS(String str) {
    long cPtr = LiKyteaJNI.Mykytea_getWS(swigCPtr, this, str);
    return (cPtr == 0) ? null : new StringVector(cPtr, true);
  }

  public TagsVector getTags(String str) {
    long cPtr = LiKyteaJNI.Mykytea_getTags(swigCPtr, this, str);
    return (cPtr == 0) ? null : new TagsVector(cPtr, true);
  }

  public TagsVector getAllTags(String str) {
    long cPtr = LiKyteaJNI.Mykytea_getAllTags(swigCPtr, this, str);
    return (cPtr == 0) ? null : new TagsVector(cPtr, true);
  }

  public String getTagsToString(String str) {
    return LiKyteaJNI.Mykytea_getTagsToString(swigCPtr, this, str);
  }

}
