/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.linkedin.kytea;

public class PairVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PairVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PairVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LiKyteaJNI.delete_PairVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PairVector() {
    this(LiKyteaJNI.new_PairVector__SWIG_0(), true);
  }

  public PairVector(long n) {
    this(LiKyteaJNI.new_PairVector__SWIG_1(n), true);
  }

  public long size() {
    return LiKyteaJNI.PairVector_size(swigCPtr, this);
  }

  public long capacity() {
    return LiKyteaJNI.PairVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    LiKyteaJNI.PairVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return LiKyteaJNI.PairVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    LiKyteaJNI.PairVector_clear(swigCPtr, this);
  }

  public void add(Pairsd x) {
    LiKyteaJNI.PairVector_add(swigCPtr, this, Pairsd.getCPtr(x), x);
  }

  public Pairsd get(int i) {
    return new Pairsd(LiKyteaJNI.PairVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Pairsd val) {
    LiKyteaJNI.PairVector_set(swigCPtr, this, i, Pairsd.getCPtr(val), val);
  }

}
