/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.linkedin.kytea;

public class Pairsd {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Pairsd(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Pairsd obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LiKyteaJNI.delete_Pairsd(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Pairsd() {
    this(LiKyteaJNI.new_Pairsd__SWIG_0(), true);
  }

  public Pairsd(String first, double second) {
    this(LiKyteaJNI.new_Pairsd__SWIG_1(first, second), true);
  }

  public Pairsd(Pairsd p) {
    this(LiKyteaJNI.new_Pairsd__SWIG_2(Pairsd.getCPtr(p), p), true);
  }

  public void setFirst(String value) {
    LiKyteaJNI.Pairsd_first_set(swigCPtr, this, value);
  }

  public String getFirst() {
    return LiKyteaJNI.Pairsd_first_get(swigCPtr, this);
  }

  public void setSecond(double value) {
    LiKyteaJNI.Pairsd_second_set(swigCPtr, this, value);
  }

  public double getSecond() {
    return LiKyteaJNI.Pairsd_second_get(swigCPtr, this);
  }

}
