/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.linkedin.kytea;

public class TagsVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TagsVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TagsVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LiKyteaJNI.delete_TagsVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TagsVector() {
    this(LiKyteaJNI.new_TagsVector__SWIG_0(), true);
  }

  public TagsVector(long n) {
    this(LiKyteaJNI.new_TagsVector__SWIG_1(n), true);
  }

  public long size() {
    return LiKyteaJNI.TagsVector_size(swigCPtr, this);
  }

  public long capacity() {
    return LiKyteaJNI.TagsVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    LiKyteaJNI.TagsVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return LiKyteaJNI.TagsVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    LiKyteaJNI.TagsVector_clear(swigCPtr, this);
  }

  public void add(Tags x) {
    LiKyteaJNI.TagsVector_add(swigCPtr, this, Tags.getCPtr(x), x);
  }

  public Tags get(int i) {
    return new Tags(LiKyteaJNI.TagsVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Tags val) {
    LiKyteaJNI.TagsVector_set(swigCPtr, this, i, Tags.getCPtr(val), val);
  }

}
