/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.linkedin.kytea;

public class Tags {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Tags(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tags obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LiKyteaJNI.delete_Tags(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSurface(String value) {
    LiKyteaJNI.Tags_surface_set(swigCPtr, this, value);
  }

  public String getSurface() {
    return LiKyteaJNI.Tags_surface_get(swigCPtr, this);
  }

  public void setTag(PairVectorVector value) {
    LiKyteaJNI.Tags_tag_set(swigCPtr, this, PairVectorVector.getCPtr(value), value);
  }

  public PairVectorVector getTag() {
    long cPtr = LiKyteaJNI.Tags_tag_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PairVectorVector(cPtr, false);
  }

  public Tags() {
    this(LiKyteaJNI.new_Tags(), true);
  }

}
